services:
  db:
    image: postgres:9.4
    container_name: gpme_db
    networks:
      - gestorpmenetwork
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: dev
      POSTGRES_DB: gestordb
    ports:
      - "5435:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  application:
    build:
      context: .
      dockerfile: Dockerfile
    image: gestorpme:1.0.1
    container_name: gpme_app
    networks:
      - gestorpmenetwork
    ports:
      - "8005:8005"
    depends_on:
      - db

networks:
  gestorpmenetwork:
    driver: bridge